### ISSUE TITLE
[Interactive] Forensic search is not update from interactive page

### ISSUE THREAD

**Issue by AFPMedialab** [AFP-Medialab/we-verify-app#20]
Selecting "Forensic search" to do not trigger forensic process.
URL is correctly set in the search area but a 404 error is set by chrome log thus content is not updated.
Processing next the URL works afterward.

Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by AFPMedialab** [comment]
https://reveal-mklab.iti.gr/reveal/imgs/example15.jpg does not exist => 404
 http 404 is not related with this process

**Comment by AFPMedialab** [comment]
set to enhancement because triggering the process would be a good to have

**Comment by ttramb** [comment]
404 is due to https://reveal-mklab.iti.gr/reveal/ which is loaded inside the IFrame.
IFrame content is loaded in the background
