### ISSUE TITLE
Display of portrait pictures in forensic pop-up

### ISSUE THREAD

**Issue by dteyssou** [AFP-Medialab/we-verify-app#222]
There is a bug display while using the GIF / mp4 export of forensic filters on portrait images that
<img width="1493" alt="Capture d’écran 2023-01-05 à 10 51 14" src="https://user-images.githubusercontent.com/1705937/210755470-6d05fc06-5e0e-4bac-897b-c6ea5c568121.png">
 are cut on display.

**Comment by ttramb** [comment]
Display component is generated an infinite loop when using CheckGif after:
```
app.bundle.js:2 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at M (app.bundle.js:2:2176038)
    at app.bundle.js:2:2176293
```

To reproduce:
1 - Process any images with forensic
2 - display export result animated Gif
3 - close export window
4 - go to CheckGif

Infinite loop is starting shows in the console
