### ISSUE TITLE
[TwitterSNA] For token refresh error, a more informative message is needed.

### ISSUE THREAD

**Issue by meminbakir** [AFP-Medialab/we-verify-app#27]
When the token expires the alert message should be more informative, currently, it says "Twitter analysis failed due to an unknown cause." This should be replaced with a message that indicates the token refresh is needed.

**Comment by AFPMedialab** [comment]
This is happening when using a server that do not have a trust ssl certificate and no domain names attached.
No issue with server domain with trusted ssl, token is refreshing correctly

**Comment by meminbakir** [comment]
I mean the alert message can be more informative. Just changing the message text should be enough, instead of "Twitter analysis failed due to an unknown cause.", it can be something like "Your access code expired! Please get a new access code!"...

**Comment by ttramb** [comment]
done in TSNA Server
