### ISSUE TITLE
(Some) Individual Tool Pages Incorrectly Load TSV String Files

### ISSUE THREAD

**Issue by greenwoodma** [AFP-Medialab/we-verify-app#58]
The loading of TSV files to provide the strings for the UI (to support multiple languages) is broken on a number of the individual tools pages (certainly on magnifier and ocr).

In the broken cases a single TSV file is loaded for the tool

```
import tsv from "../../../../LocalDictionary/components/NavItems/tools/Magnifier.tsv";
```

which is then used in two `useLoadLanguage` calls as follows

```
const keyword = useLoadLanguage("components/NavItems/tools/Magnifier.tsv", tsv);
const keywordAllTools = useLoadLanguage("components/NavItems/tools/Alltools.tsv", tsv);
```

This leads to issues with text not appearing in the UI. Exact errors depend on which order pages are loaded in.

If you access the main tools page (i.e. the one that lists all the tools) then you may see no problem as that page will correctly load the right TSV file and cache it against the `components/NavItems/tools/Alltools.tsv` key and then the values will still be available when you load a tool irrespective of the content of the `tsv` variable.

If, however, you manage to load a specific tool prior to loading the main tools page, then in the cache we accidentally end up storing the contents of (in this example) `Magnifier.tsv` against `components/NavItems/tools/Alltools.tsv`. This means that any use of `keywordAllTools` on this page will return the empty string as shown below:

![Screenshot from 2021-07-08 15-40-46](https://user-images.githubusercontent.com/3025272/124941755-f3d04080-e002-11eb-9dff-ccf622f6021c.png)

 Even worse though, if you then switch back to the main tools page all the text is missing

![Screenshot from 2021-07-08 15-40-52](https://user-images.githubusercontent.com/3025272/124941834-03e82000-e003-11eb-8d9e-a3a17f18bf47.png)

This can be fixed by loading both TSV files into separate variables and associating each with the correct key in the cache. As I said I've noticed OCR and Magnifier so far that have this problem, but I've not checked the other tools or pages.

**Comment by AFPMedialab** [comment]
Fix in master and dev-rc. 
Issues with reducer variable instantiation that failed to be detected by react renderer #64
