### ISSUE TITLE
[Contextual Menu] Error message is empty if using non supported URL

### ISSUE THREAD

**Issue by AFPMedialab** [AFP-Medialab/we-verify-app#66]
Selected unsupported content from contextual menu for:
- Magnifier
- Forensic
Give a empty error message as follow:
<img width="1424" alt="Capture d’écran 2021-09-09 à 10 20 52" src="https://user-images.githubusercontent.com/40788591/132650084-322290dd-d699-410e-af28-d2edd2943d25.png">
Submit the same content gives the expected error

**Comment by AFPMedialab** [comment]
In this use case, the contextual menu should not been activate if the url is not an image

**Comment by nietoarranz** [comment]
Solved in the last commit
