### ISSUE TITLE
Upgrade react-hook-form to 7.15.3

### ISSUE THREAD

**Issue by AFPMedialab** [AFP-Medialab/we-verify-app#69]
Upgrade react-hook-form to v 7.15.x required a code change
see: https://react-hook-form.com/migrate-v6-to-v7/

Component: AdvancedTools.js need to be rewrite to support new feature

**Comment by nietoarranz** [comment]
Fixed in commit https://github.com/AFP-Medialab/we-verify-app/commit/4e1f6b75124d37d0cd60dced974686f75a9c4c19
